from settings import *
from level_settings import *
from graphic import *
from main_hero import *
from button import *
from settings import *
from enemy import *
from vilagers import *
from music import *
from tasks import *
from boss import *
from sounds import *
from shop import *